### ISSUE TITLE
In-docker build and run support

### ISSUE THREAD

**Issue by vetermanve** [abertschi/graalphp#18]
Can I help and add the Dockerfile and docker-compose to have an ability to UP this project in docker? 
What Java configuration and dependencies are required for building this project?

**Comment by abertschi** [comment]
Hi there,

Thanks for shouting out :rocket: 

Take a look at these files:

- travis: https://github.com/abertschi/graalphp/blob/master/.travis.yml
- local: https://github.com/abertschi/graalphp/blob/master/tools/build-local.sh

As for build dependencies:
- linux environment, travis runs ubuntu
- graalvm (java 11), maven 3+

**Comment by vetermanve** [comment]
Cool @abertschi !
But what for most of the code is hidden under GRAALPHP_BUILD_NATIVE env variable check?

**Comment by abertschi** [comment]
`GRAALPHP_BUILD_NATIVE` instructs `native-image` to make a AOT compilation of the project. See the `graalphp-native` maven module.

https://github.com/abertschi/graalphp/blob/835eb75f87da5d30e2be96c62634ad6b45d4003a/graalphp-native/make_native.sh#L5-L15

For a docker setup all dependencies listed in the travis file should suffice. 
travis run Ubuntu Xenial 16.04.

native-image is downloaded here:

https://github.com/abertschi/graalphp/blob/835eb75f87da5d30e2be96c62634ad6b45d4003a/.travis.yml#L18-L25

**Comment by vetermanve** [comment]
No, the question in not about WHAT this flag is doing, the question is why you need this flag if there is anywhere - in build script and CI it's hardcoded to the TRUE value. 

The question is why not just to remove all of those if statements and make building a bit more clear?

**Comment by vetermanve** [comment]
Oh I see there is not only those CI and build scripts are involved in this process, but overall it'll be good to clarify somewhere meaning of native and non-native builds =)

**Comment by abertschi** [comment]
This project is my thesis and is subject to heavy change.

**Comment by vetermanve** [comment]
No problems =)

**Comment by abertschi** [comment]
#46
